apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: devops-kargo
  namespace: devops-kargo
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
    - stageSelector:
        name: staging
      autoPromotionEnabled: true
    - stageSelector:
        name: prod
      autoPromotionEnabled: false