apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: devops-kargo # Ensure this is the correct namespace
  annotations:
    kargo.akuity.io/color: lime
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: devops-app-ghcr
      sources:
        direct: false
        stages:
          - dev
  
  promotionTemplate:
    spec:
      steps:
        # 1. Clone the configuration repository
        - uses: git-clone
          config:
            repoURL: https://github.com/laprus/devops-config
            checkout:
              # Kargo ensures that the version cloned here is the specific Freight
              # approved for this promotion (the one that 'dev' successfully used).
              - branch: main
                path: ./repo
        
        # 2. Update the 'image.tag' in the values file for the 'staging' environment.
        # It uses the tag from the image source present in the approved Freight.
        - uses: yaml-update
          config:
            path: ./repo/environments/staging/values.yaml # Target the staging config file
            updates:
              # Pull the image tag from the Freight object. 
              # It should be the same tag that was promoted to 'dev'.
              - key: image.tag
                value: ${{ imageFrom("ghcr.io/laprus/devops/devops-app").Tag }}
        
        # 3. Commit the changes to the configuration repository
        - uses: git-commit
          config:
            path: ./repo
            message: "chore: promote devops-app to staging - ${{ imageFrom(\"ghcr.io/laprus/devops/devops-app\").Tag }}"
        
        # 4. Push the commit back to the 'devops-config' repository
        - uses: git-push
          config:
            path: ./repo
        
        # 5. Trigger an ArgoCD sync for the 'staging' application.
        # This forces ArgoCD to reconcile and pick up the new values.yaml file 
        # from the 'devops-config' repository, which was just updated.
        - uses: argocd-update
          config:
            apps:
              # The name of the Application generated by your ApplicationSet (devops-app-staging)
              - name: devops-app-staging
                sources:
                  # Point to the main repository defined in your ApplicationSet (the Chart repo)
                  - repoURL: "https://github.com/laprus/devops.git"