apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: devops-kargo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: devops-app-ghcr
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/laprus/devops-config
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/environments/dev/values.yaml
            updates:
              - key: image.tag
                value: ${{ imageFrom("ghcr.io/laprus/devops/devops-app").Tag }}
        - uses: git-commit
          config:
            path: ./repo
            message: "chore: promote devops-app to dev - ${{ imageFrom(\"ghcr.io/laprus/devops/devops-app\").Tag }}"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: devops-app-dev
                namespace: devops-dev
                sources:
                - repoURL: "https://github.com/laprus/devops-config"
              
